config/routes.rb
Movies::Application.routes.draw do
  resources :movies
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
   root :to => "movies#index"

  # See how all your routes lay out with "rake routes"
end

app/models/cached_web.rb
class CachedWeb
  
  @@min_wait_times = {}
  @@last_request_times = {}
 
  def escape_key(key)
    if key.size > 140
      Digest::MD5.hexdigest(key)
    else
      key.gsub(/[^a-z0-9]/i,"_")
    end
  end
  
  def self.get(params)
    CachedWeb.new.get(params)
  end
  
  def get(params)
    url = params[:url].gsub(" ","%20").gsub("%off", "%25off")
    page, redirect_url, headers = get_cache(:url=>url, :expires_in=>params[:expires_in], :details=>true) rescue [nil, nil, nil]
    
    if params[:cache_only]
      return [nil, nil, nil] if page.blank?
      return [page, redirect_url, headers]
    end

    if page.blank?
      uri = URI.parse(url)
      domain = uri.host.downcase
      #puts "Not in cache - getting: #{params[:url]}"
      # Don't hit a site more than once per 5 seconds
      time_to_wait = (@@min_wait_times[domain] || 5) -
        (Time.now - (@@last_request_times[domain] || Time.at(0)))

      puts "#{Time.now} - (#{@@last_request_times[domain]}) = #{ (Time.now - (@@last_request_times[domain].to_i)) }"

      if time_to_wait > 0  
        puts "Waiting for #{time_to_wait} on domain #{domain}"
        sleep time_to_wait
      end
      
      @agent = Mechanize.new unless @agent
      page = @agent.get(url) 
      @@last_request_times[domain] = Time.now
      content = page.body
      redirect_url = page.uri.to_s
      headers = page.header
      set_cache(:url=>url, :redirect_url=>redirect_url, :headers=>headers, :content=>content)
      [content, redirect_url, headers]
    else
      [page, redirect_url, headers]
    end
  end

  def self.fetch_cache(params, &block)
    CachedWeb.new.fetch_cache(params, &block)
  end

  def fetch_cache(params)
    ret_val = nil
    begin
      ret_val = get_cache(params)
    rescue
      puts "didn't find data in cache: #{$!}"
    end
    unless ret_val
      ret_val = yield self
      set_cache(params.merge(:content=>ret_val))
    end
    
    return ret_val
  end
  
  def post(url, params)
    puts "Not in cache - POSTing to: #{url}"
    @agent = Mechanize.new unless @agent
    begin
      page = @agent.post(url, params)
      uri = URI.parse(url)
      @@last_request_times[uri.host]
      content = page.body
      redirect_url = page.uri.to_s
      headers = page.header
      set_cache(:url=>url, :redirect_url=>redirect_url, :headers=>headers, :content=>content)
      [content, redirect_url, headers]
    rescue Exception => e
      puts e
      puts e.backtrace
      Toadhopper(AIRBRAKE_KEY).post!(e)
      ["", url, {}]
    end
  end

  def set_cache(params)
    key = escape_key(params[:url].present? ? params[:url] : params[:key])
    content = params[:content]
    redirect_url = params[:redirect_url]
  
    h = {:content => content, :redirect_url=>redirect_url}
  
  
    path = "/tmp/cachedweb/#{key}"
    #puts "Saving file to #{path}"
    begin
      File.open(path, 'w') do |out|
         YAML.dump(h, out)
      end
    rescue Exception
      `mkdir -p /tmp/cachedweb`
      File.open(path, 'w') do |out|
         YAML.dump(h, out)
      end
    end
    true
  end
  
  def get_cache(params)
    key = escape_key(params[:url].present? ? params[:url] : params[:key])
    details = params[:details]
    expires_in = params[:expires_in]
  
    timestamp = nil

    path = "/tmp/cachedweb/#{key}"
    timestamp = File.ctime(path)

    if expires_in and timestamp.nil?
      #puts "There is no timestamp, force a get of this URL so we can add a timestamp"
      throw "There is no timestamp, force a get of this URL so we can add a timestamp"
    end
  
    if expires_in and timestamp and timestamp < (Time.now - expires_in)
      #puts "Cache is older than desired, saved on #{timestamp}"
      throw "Cache is older than desired, saved on #{timestamp}"
    end
  
    h = YAML::load_file(path)
    content = h[:content]
    redirect_url = h[:redirect_url]
    if details
      [content, redirect_url, nil]
    else
      content
    end
  end

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  serialize :runtime
  serialize :genres
  serialize :language
  serialize :writers
  serialize :directors
  serialize :actors
  serialize :country
  serialize :also_known_as
  serialize :episodes

  include Tire::Model::Search
  include Tire::Model::Callbacks

  def self.search(params)
    tire.search(load: true) do
      query { string params[:query], default_operator: "AND" } if params[:query].present?
    end
  end

  def self.create_from_title(intitle)
    url = "http://imdbapi.org/?q=#{intitle}"
    content, redirect_url, headers  = CachedWeb.get(:url=>url)
    ret = JSON.parse(content)
    if m = ret.first and (not ret.is_a?(Hash))
      puts "Create movie: #{m}"
      if movie = Movie.find_by_title(m['title'].to_s)
        return movie
      else
        @movie = Movie.new(m)
        return @movie
      end
    end
    return nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # GET /movies
  # GET /movies.xml
  def index
    if params[:query].present?
      @movies = Movie.search(params)
    else
      @movies = Movie.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.xml
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.xml
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.xml
  def create
    title = params[:movie][:title]
    if movie = Movie.create_from_title(title)
      @movie = movie
    else
      @movie = Movie.new(params[:movie])
    end

    respond_to do |format|
      if @movie.save
        format.html { redirect_to(@movie, :notice => 'Movie was successfully created.') }
        format.xml  { render :xml => @movie, :status => :created, :location => @movie }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @movie.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.xml
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to(@movie, :notice => 'Movie was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @movie.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.xml
  def destory
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to(movies_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movies</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>

<%= form_tag movies_path, method: :get do %>
  <p>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>

<table>
  <tr>
    <th>Title</th>
    <th>Year</th>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movies.each do |movie| %>
  <tr>
    <td><%= movie.title %></td>
    <td><%= movie.year %></td>
    <td><%= movie.rating %></td>
    <td><%= movie.plot_simple %></td>
    <td><%= movie.actors ? movie.actors.to_sentence : "" %></td>
    <td><%= link_to 'Show', movie %></td>
    <td><a href="<%= movie.imdb_url%>" target=_blank><img src="<%= movie.poster %>" height="75px"/></a></td>
    <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    <td><%= link_to 'Destroy', movie, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<a href="<%=@movie.imdb_url%>""><img src="<%= @movie.poster%>"/></a>
<p>
  <b>Title:</b>
  <%= @movie.title %>
</p>

<p>
  <b>Year:</b>
  <%= @movie.year %>
</p>

<p>
  <b>Rating:</b>
  <%= @movie.rating %>
</p>


<p>
  <b>Plot:</b>
  <%= @movie.plot_simple %>
</p>

<p>
  <b>directors:</b>
  <%= @movie.directors ? @movie.directors.to_sentence : "" %>
</p>

<p>
  <b>actors:</b>
  <%= @movie.actors ? @movie.actors.to_sentence : "" %>
</p>

<p>
  <b>country:</b>
  <%= @movie.country ? @movie.country.to_sentence : "" %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>